# Base configs
baseurl: "https://rorobig.github.io/saycheese/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-229153844-1" 




# UI configs
title: "Photography by Rocheandley Kwidama"
subtitle: "See the world through my eyes!"
author: "Rocheandley Kwidama"
header:
 title: "Photography"
 subtitle: "by Rocheandley Kwidama"
footer:
 name: "Anyong haseyo, my name is Roro"
 bio: "I'm  an engineer and a tech aficionado from Curaçao. Love everything platform and cybersecurity related and solving intricate problems in life and now learning photography."
 github: "https://www.github.com/rorobig"
web_design: "rk"
social_urls:
  facebook: "https://www.facebook.com/rocheandley.kwidama"
  twitter: "https://www.twitter.com/Walking_dolphin"
  instagram: "https://www.instagram.com/skittlesmclovingit"
  linkedin: "https://in.linkedin.com/in/rocheandley-kwidama"
  github: "https://www.github.com/rorobig"
